version: "2.4"
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: "root-ca-list"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "dbuser"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: "mysql -u root -e \"SELECT 1;\""
      interval: 3s
      timeout: 1s
      retries: 6
      start_period: 8s
  ca-list:
    build: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "./application.yaml:/conf/application.yaml"
    ports:
      - "8080:8080"
